/**
 * Unit tests for src/tests/matcher.ts
 *
 * The matcher accepts an optional FsAdapter parameter for filesystem
 * injection.  Tests pass a virtual adapter — no real filesystem is touched and
 * no Node built-in mocking is required.  All inputs are controlled fixtures so
 * the tests are fully deterministic.
 *
 * Coverage checklist (per task requirements):
 *  ✓ direct .test filename match
 *  ✓ direct .spec filename match
 *  ✓ test file located under tests/
 *  ✓ JS/TS/JSX/TSX extensions
 *  ✓ nested source directories
 *  ✓ import-based matching (ES import)
 *  ✓ require() matching
 *  ✓ multiple matching tests
 *  ✓ no matching tests
 *  ✓ duplicate prevention
 *  ✓ multiple affected files sharing a test file
 *  ✓ deterministic ordering
 *  ✓ deleted/missing affected file (matcher is path-based, not presence-based for source)
 *  ✓ Windows path normalization
 *  ✓ arbitrary files containing "test" are not treated as tests
 */

import { describe, it, expect } from 'vitest';
import * as path from 'path';
import type { AffectedFile } from '../../src/types.js';
import { matchTests, conventionCandidates, testFileImportsSource } from '../../src/tests/matcher.js';
import type { FsAdapter } from '../../src/tests/matcher.js';

// ---------------------------------------------------------------------------
// Virtual filesystem helpers
// ---------------------------------------------------------------------------

/**
 * Use a virtual repo root that is consistent with what path.resolve() would
 * produce for it, so all paths generated by the matcher (which uses path.join
 * and path.resolve internally) key against the same values in the adapter.
 *
 * On POSIX: path.resolve('/virtual-repo') === '/virtual-repo'.
 * On Windows: path.resolve('/virtual-repo') === 'C:\\virtual-repo'.
 *
 * We deliberately use a path that will never exist on disk and call
 * path.resolve on it so the adapter keys always match.
 */
const REPO_RAW = '/virtual-cpf-test-repo';
const REPO = path.resolve(REPO_RAW);

/** Normalise any path to forward-slash representation for adapter key lookup. */
function norm(p: string): string {
  return p.replace(/\\/g, '/');
}

/** Build an absolute path under REPO from a POSIX-relative path. */
function repoPath(rel: string): string {
  // Join each POSIX segment individually so path.join handles OS separators.
  return path.join(REPO, ...rel.split('/'));
}

/** Build a minimal AffectedFile fixture. */
function af(p: string, depth = 0): AffectedFile {
  return { path: p, depth };
}

/**
 * Build a virtual FsAdapter from a list of POSIX-relative file paths and an
 * optional map of POSIX-relative path → file content.
 *
 * `existsSync` returns true for any path that maps to one of existingFiles.
 * `readdirSync` returns a virtual directory listing derived from existingFiles.
 * `readFileSync` returns content from fileContents (keyed by POSIX-relative path).
 */
function makeFs(
  existingFiles: string[],
  // Keys are POSIX-relative to repo root, e.g. 'tests/foo.test.ts'
  fileContents: Record<string, string> = {},
): FsAdapter {
  // Canonical absolute paths that "exist" — keyed by norm(absPath).
  const existing = new Set(existingFiles.map((f) => norm(repoPath(f))));

  // Build a directory tree: Map<norm(absDir), Entry[]>
  const dirTree = new Map<string, Array<{ name: string; isDir: boolean }>>();

  function ensureDir(normDir: string): void {
    if (!dirTree.has(normDir)) dirTree.set(normDir, []);
  }

  for (const rel of existingFiles) {
    const parts = rel.split('/');
    let current = norm(REPO);
    ensureDir(current);

    for (let i = 0; i < parts.length - 1; i++) {
      const segment = parts[i]!;
      const childNorm = `${current}/${segment}`;
      const parentEntries = dirTree.get(current)!;
      if (!parentEntries.some((e) => e.name === segment)) {
        parentEntries.push({ name: segment, isDir: true });
      }
      ensureDir(childNorm);
      current = childNorm;
    }

    const fileName = parts[parts.length - 1]!;
    dirTree.get(current)!.push({ name: fileName, isDir: false });
  }

  // Build a content map keyed by norm(absPath) for readFileSync.
  const contentMap: Record<string, string> = {};
  for (const [rel, content] of Object.entries(fileContents)) {
    contentMap[norm(repoPath(rel))] = content;
  }

  return {
    existsSync(p: string): boolean {
      return existing.has(norm(p));
    },

    readdirSync(dir: string) {
      const key = norm(dir);
      return (dirTree.get(key) ?? []).map(({ name, isDir }) => ({
        name,
        isDirectory: () => isDir,
        isFile: () => !isDir,
      }));
    },

    readFileSync(p: string, _enc: 'utf8'): string {
      const key = norm(p);
      if (key in contentMap) return contentMap[key]!;
      throw Object.assign(new Error(`ENOENT: ${key}`), { code: 'ENOENT' });
    },
  };
}

// ---------------------------------------------------------------------------
// Empty input
// ---------------------------------------------------------------------------

describe('empty affected list', () => {
  it('returns an empty array when there are no affected files', () => {
    const result = matchTests([], REPO, makeFs([]));
    expect(result).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// Convention: .test match
// ---------------------------------------------------------------------------

describe('filename convention — .test', () => {
  it('matches src/foo.test.ts alongside the source file', () => {
    const result = matchTests([af('src/foo.ts')], REPO, makeFs(['src/foo.test.ts']));
    expect(result).toHaveLength(1);
    expect(result[0]!.affectedFile).toBe('src/foo.ts');
    expect(result[0]!.testFiles).toContain('src/foo.test.ts');
  });

  it('matches tests/foo.test.ts under the tests/ root directory', () => {
    const result = matchTests([af('src/foo.ts')], REPO, makeFs(['tests/foo.test.ts']));
    expect(result[0]!.testFiles).toContain('tests/foo.test.ts');
  });
});

// ---------------------------------------------------------------------------
// Convention: .spec match
// ---------------------------------------------------------------------------

describe('filename convention — .spec', () => {
  it('matches src/foo.spec.ts alongside the source file', () => {
    const result = matchTests([af('src/foo.ts')], REPO, makeFs(['src/foo.spec.ts']));
    expect(result[0]!.testFiles).toContain('src/foo.spec.ts');
  });

  it('matches tests/foo.spec.ts under the tests/ root directory', () => {
    const result = matchTests([af('src/foo.ts')], REPO, makeFs(['tests/foo.spec.ts']));
    expect(result[0]!.testFiles).toContain('tests/foo.spec.ts');
  });
});

// ---------------------------------------------------------------------------
// Extensions: JS/JSX/TSX
// ---------------------------------------------------------------------------

describe('file extensions', () => {
  it('matches .test.js for a .js source file', () => {
    const result = matchTests([af('src/util.js')], REPO, makeFs(['src/util.test.js']));
    expect(result[0]!.testFiles).toContain('src/util.test.js');
  });

  it('matches .test.jsx for a .jsx source file', () => {
    const result = matchTests([af('src/Button.jsx')], REPO, makeFs(['src/Button.test.jsx']));
    expect(result[0]!.testFiles).toContain('src/Button.test.jsx');
  });

  it('matches .test.tsx for a .tsx source file', () => {
    const result = matchTests([af('src/Form.tsx')], REPO, makeFs(['src/Form.test.tsx']));
    expect(result[0]!.testFiles).toContain('src/Form.test.tsx');
  });

  it('matches .spec.ts for a .ts source file', () => {
    const result = matchTests([af('src/parser.ts')], REPO, makeFs(['src/parser.spec.ts']));
    expect(result[0]!.testFiles).toContain('src/parser.spec.ts');
  });
});

// ---------------------------------------------------------------------------
// Nested source directories
// ---------------------------------------------------------------------------

describe('nested source directories', () => {
  it('matches tests/graph/traversal.test.ts for src/graph/traversal.ts', () => {
    const result = matchTests(
      [af('src/graph/traversal.ts')],
      REPO,
      makeFs(['tests/graph/traversal.test.ts']),
    );
    expect(result[0]!.testFiles).toContain('tests/graph/traversal.test.ts');
  });

  it('matches src/a/b/c.test.ts alongside a deeply nested source file', () => {
    const result = matchTests([af('src/a/b/c.ts')], REPO, makeFs(['src/a/b/c.test.ts']));
    expect(result[0]!.testFiles).toContain('src/a/b/c.test.ts');
  });

  it('strips the top-level segment for tests/ mapping: lib/foo/bar.ts → tests/foo/bar.test.ts', () => {
    const result = matchTests([af('lib/foo/bar.ts')], REPO, makeFs(['tests/foo/bar.test.ts']));
    expect(result[0]!.testFiles).toContain('tests/foo/bar.test.ts');
  });
});

// ---------------------------------------------------------------------------
// Import-based matching
// ---------------------------------------------------------------------------

describe('import-based matching', () => {
  it('finds a test that uses ES import with from clause pointing to the source', () => {
    // tests/utils/helper.other.test.ts imports src/utils/helper — relative: ../../src/utils/helper
    const testContent = `import { foo } from '../../src/utils/helper';\n`;
    const fs = makeFs(
      ['tests/utils/helper.other.test.ts'],
      { 'tests/utils/helper.other.test.ts': testContent },
    );
    const result = matchTests([af('src/utils/helper.ts')], REPO, fs);
    expect(result[0]!.testFiles).toContain('tests/utils/helper.other.test.ts');
  });

  it('finds a test that imports with the .ts extension included', () => {
    // tests/foo.other.test.ts importing ../src/foo.ts (one level up from tests/ to repo root)
    const testContent = `import type { Foo } from '../src/foo.ts';\n`;
    const fs = makeFs(
      ['tests/foo.other.test.ts'],
      { 'tests/foo.other.test.ts': testContent },
    );
    const result = matchTests([af('src/foo.ts')], REPO, fs);
    expect(result[0]!.testFiles).toContain('tests/foo.other.test.ts');
  });

  it('finds a test that uses require() pointing to the source', () => {
    // tests/bar.test.ts requires ../src/utils/bar — relative from tests/ to src/utils/bar
    const testContent = `const { bar } = require('../src/utils/bar');\n`;
    const fs = makeFs(
      ['tests/bar.test.ts'],
      { 'tests/bar.test.ts': testContent },
    );
    const result = matchTests([af('src/utils/bar.ts')], REPO, fs);
    expect(result[0]!.testFiles).toContain('tests/bar.test.ts');
  });

  it('does NOT match a test whose import does not resolve to the source', () => {
    const testContent = `import { x } from './other';\n`;
    const fs = makeFs(
      ['tests/unrelated.test.ts'],
      { 'tests/unrelated.test.ts': testContent },
    );
    const result = matchTests([af('src/foo.ts')], REPO, fs);
    expect(result[0]!.testFiles).toHaveLength(0);
  });
});

// ---------------------------------------------------------------------------
// No matching tests
// ---------------------------------------------------------------------------

describe('no matching tests', () => {
  it('returns an empty testFiles array when no test files exist', () => {
    const result = matchTests([af('src/foo.ts')], REPO, makeFs([]));
    expect(result).toHaveLength(1);
    expect(result[0]!.affectedFile).toBe('src/foo.ts');
    expect(result[0]!.testFiles).toEqual([]);
  });

  it('returns empty testFiles for a source file with no naming-convention match', () => {
    const result = matchTests(
      [af('src/foo.ts')],
      REPO,
      makeFs(['src/bar.test.ts'], { 'src/bar.test.ts': '' }),
    );
    expect(result[0]!.testFiles).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// Multiple matching tests
// ---------------------------------------------------------------------------

describe('multiple matching tests', () => {
  it('returns all matching test files for a single source file', () => {
    const result = matchTests(
      [af('src/foo.ts')],
      REPO,
      makeFs(['src/foo.test.ts', 'src/foo.spec.ts', 'tests/foo.test.ts']),
    );
    const files = result[0]!.testFiles;
    expect(files).toContain('src/foo.test.ts');
    expect(files).toContain('src/foo.spec.ts');
    expect(files).toContain('tests/foo.test.ts');
    expect(files).toHaveLength(3);
  });
});

// ---------------------------------------------------------------------------
// Duplicate prevention
// ---------------------------------------------------------------------------

describe('duplicate prevention', () => {
  it('does not duplicate a test file matched by both convention and import', () => {
    // src/foo.test.ts exists (convention match) AND imports src/foo.ts (import match).
    const testContent = `import { foo } from './foo';\n`;
    const result = matchTests(
      [af('src/foo.ts')],
      REPO,
      makeFs(['src/foo.test.ts'], { 'src/foo.test.ts': testContent }),
    );
    const files = result[0]!.testFiles;
    expect(new Set(files).size).toBe(files.length); // all unique
    expect(files).toContain('src/foo.test.ts');
    expect(files).toHaveLength(1);
  });
});

// ---------------------------------------------------------------------------
// Multiple affected files sharing a test file
// ---------------------------------------------------------------------------

describe('multiple affected files sharing a test file', () => {
  it('maps a shared test file to each relevant affected file independently', () => {
    // tests/shared.test.ts imports ../src/a and ../src/b (one level up from tests/)
    const sharedContent =
      `import { a } from '../src/a';\nimport { b } from '../src/b';\n`;
    const fs = makeFs(
      ['tests/shared.test.ts'],
      { 'tests/shared.test.ts': sharedContent },
    );
    const result = matchTests([af('src/a.ts'), af('src/b.ts')], REPO, fs);
    expect(result).toHaveLength(2);
    expect(result[0]!.testFiles).toContain('tests/shared.test.ts');
    expect(result[1]!.testFiles).toContain('tests/shared.test.ts');
  });
});

// ---------------------------------------------------------------------------
// Deterministic ordering
// ---------------------------------------------------------------------------

describe('deterministic ordering', () => {
  it('returns testFiles sorted alphabetically', () => {
    const result = matchTests(
      [af('src/foo.ts')],
      REPO,
      makeFs(['src/foo.spec.ts', 'src/foo.test.ts', 'tests/foo.test.ts']),
    );
    const files = result[0]!.testFiles;
    expect(files).toEqual([...files].sort());
  });

  it('returns TestMatch[] in the same order as the affected input', () => {
    const result = matchTests(
      [af('src/alpha.ts'), af('src/beta.ts')],
      REPO,
      makeFs(['src/alpha.test.ts', 'src/beta.test.ts']),
    );
    expect(result[0]!.affectedFile).toBe('src/alpha.ts');
    expect(result[1]!.affectedFile).toBe('src/beta.ts');
  });
});

// ---------------------------------------------------------------------------
// Deleted / missing affected file
// ---------------------------------------------------------------------------

describe('deleted / missing affected file', () => {
  it('returns an entry with empty testFiles when the source file is missing (deleted)', () => {
    const result = matchTests([af('src/deleted.ts')], REPO, makeFs([]));
    expect(result).toHaveLength(1);
    expect(result[0]!.affectedFile).toBe('src/deleted.ts');
    expect(result[0]!.testFiles).toEqual([]);
  });

  it('still returns naming-convention matches for a deleted file if the test file exists', () => {
    const result = matchTests(
      [af('src/deleted.ts')],
      REPO,
      makeFs(['src/deleted.test.ts']),
    );
    expect(result[0]!.testFiles).toContain('src/deleted.test.ts');
  });
});

// ---------------------------------------------------------------------------
// Windows path normalization
// ---------------------------------------------------------------------------

describe('Windows path normalization', () => {
  it('normalises Windows backslash paths in affectedFile to forward slashes', () => {
    const result = matchTests(
      [af('src\\utils\\helper.ts')],
      REPO,
      makeFs(['src/utils/helper.test.ts']),
    );
    expect(result[0]!.affectedFile).toBe('src/utils/helper.ts');
  });

  it('finds convention matches for Windows-style affected paths', () => {
    const result = matchTests(
      [af('src\\utils\\helper.ts')],
      REPO,
      makeFs(['src/utils/helper.test.ts']),
    );
    expect(result[0]!.testFiles).toContain('src/utils/helper.test.ts');
  });
});

// ---------------------------------------------------------------------------
// Arbitrary files containing "test" in their name are NOT treated as tests
// ---------------------------------------------------------------------------

describe('non-test files are not treated as tests', () => {
  it('ignores a file whose name contains "test" but does not match *.test.* or *.spec.*', () => {
    // "testimonial.ts" contains "test" but is not a test file.
    const result = matchTests([af('src/foo.ts')], REPO, makeFs(['src/testimonial.ts']));
    expect(result[0]!.testFiles).toEqual([]);
  });

  it('ignores a directory named "testutils" containing non-test files', () => {
    const result = matchTests(
      [af('src/foo.ts')],
      REPO,
      makeFs(['src/testutils/helpers.ts']),
    );
    expect(result[0]!.testFiles).toEqual([]);
  });

  it('does not treat a file like "testhelper.ts" as a test file', () => {
    const result = matchTests([af('src/foo.ts')], REPO, makeFs(['src/testhelper.ts']));
    expect(result[0]!.testFiles).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// Input immutability
// ---------------------------------------------------------------------------

describe('input immutability', () => {
  it('does not mutate the affected array', () => {
    const input: AffectedFile[] = [af('src/foo.ts'), af('src/bar.ts')];
    const snapshot = JSON.stringify(input);
    matchTests(input, REPO, makeFs([]));
    expect(JSON.stringify(input)).toBe(snapshot);
  });
});

// ---------------------------------------------------------------------------
// Unit tests for exported pure helpers (no filesystem needed)
// ---------------------------------------------------------------------------

describe('conventionCandidates (pure helper)', () => {
  it('produces .test.ts and .spec.ts alongside the source', () => {
    const candidates = conventionCandidates('src/foo.ts');
    expect(candidates).toContain('src/foo.test.ts');
    expect(candidates).toContain('src/foo.spec.ts');
  });

  it('produces tests/ variants when source has a leading directory', () => {
    const candidates = conventionCandidates('src/foo.ts');
    expect(candidates).toContain('tests/foo.test.ts');
    expect(candidates).toContain('tests/foo.spec.ts');
  });

  it('returns empty array for an unrecognised extension', () => {
    expect(conventionCandidates('src/foo.py')).toEqual([]);
  });
});

describe('testFileImportsSource (pure helper)', () => {
  it('returns true when content contains a bare import matching the source', () => {
    const testAbs = repoPath('tests/foo.test.ts');
    const srcAbs = repoPath('src/foo.ts');
    // The import specifier is relative from tests/ to src/:  ../../src/foo
    // On any OS, path.resolve(dirname(testAbs), '../../src/foo') === srcAbs-without-ext.
    const rel = path.relative(path.dirname(testAbs), repoPath('src/foo'));
    const content = `import { x } from './${rel.replace(/\\/g, '/')}';\n`;
    const adapter: FsAdapter = {
      existsSync: () => false,
      readdirSync: () => [],
      readFileSync: () => content,
    };
    expect(testFileImportsSource(testAbs, srcAbs, adapter)).toBe(true);
  });

  it('returns false when no import resolves to the source', () => {
    const testAbs = repoPath('tests/foo.test.ts');
    const srcAbs = repoPath('src/foo.ts');
    const content = `import { x } from './other';\n`;
    const adapter: FsAdapter = {
      existsSync: () => false,
      readdirSync: () => [],
      readFileSync: () => content,
    };
    expect(testFileImportsSource(testAbs, srcAbs, adapter)).toBe(false);
  });

  it('returns false when readFileSync throws', () => {
    const testAbs = repoPath('tests/foo.test.ts');
    const srcAbs = repoPath('src/foo.ts');
    const adapter: FsAdapter = {
      existsSync: () => false,
      readdirSync: () => [],
      readFileSync: () => { throw new Error('ENOENT'); },
    };
    expect(testFileImportsSource(testAbs, srcAbs, adapter)).toBe(false);
  });

  it('matches when the import specifier includes a source extension (.ts)', () => {
    // Some code uses 'from ../../src/foo.ts' explicitly (e.g. Deno style).
    const testAbs = repoPath('tests/foo.test.ts');
    const srcAbs = repoPath('src/foo.ts');
    const rel = path.relative(path.dirname(testAbs), repoPath('src/foo.ts'));
    const content = `import type { Foo } from './${rel.replace(/\\/g, '/')}';\n`;
    const adapter: FsAdapter = {
      existsSync: () => false,
      readdirSync: () => [],
      readFileSync: () => content,
    };
    expect(testFileImportsSource(testAbs, srcAbs, adapter)).toBe(true);
  });
});
